version: '3.8'

services:
  backend:
    build: ./Back-end
    ports:
      - "3000:3000"
    env_file:
      - ./Back-end/.env
    volumes:
      - ./Back-end:/app
    depends_on:
      - database

  frontend:
    build: ./Srisuwan
    ports:
      - "5173:5173"
    env_file:
      - ./Srisuwan/.env
    volumes:
      - ./Srisuwan:/app
    depends_on:
      - backend

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
